markdown: kramdown
base_url: http://www.wenigeristweniger.de

description: "Weniger"
root_desc: "Weniger ist weniger blog"
    
exclude: ['Rakefile', 'vendor', "Gemfile", "Gemfile.lock", "s3_website.yml"]

permalink: /artikel/:title
